# Generated by Django 4.1.7 on 2025-01-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0003_alter_staff_departmentid"),
        ("Finance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="ManagerId",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="HR.staff",
            ),
        ),
    ]
