# Generated by Django 4.1.7 on 2025-01-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Inventory", "0001_initial"),
        ("Procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="SupplierId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Procurement.supplier",
            ),
        ),
    ]
