# Generated by Django 4.1.7 on 2025-01-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "StaffId",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("StaffName", models.CharField(max_length=200)),
                ("Role", models.CharField(max_length=200)),
                ("Salary", models.CharField(max_length=15)),
                ("HireDate", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
