# Generated by Django 4.1.7 on 2025-01-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Finance", "0002_initial"),
        ("HR", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="DepartmentId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Finance.department",
            ),
        ),
    ]
