# Generated by Django 4.1.7 on 2025-01-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Finance", "0003_alter_department_managerid"),
        ("HR", "0003_alter_staff_departmentid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="DepartmentId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Finance.department",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="Salary",
            field=models.IntegerField(),
        ),
    ]
