# Generated by Django 4.1.7 on 2025-01-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0004_alter_staff_departmentid_alter_staff_salary"),
        ("Sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="StaffId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="HR.staff",
            ),
        ),
    ]
